#Server name
#Choose between the UKnet server: Earth, Building, Lobby, Minigames
server_name: Earth

#Collision between players enabled/disabled
collision: disabled

#MySQL is manditory for this plugin
#Login information
MySQL_host: localhost
MySQL_port: 3306
MySQL_username: root
MySQL_password: password

#Database name (doesn't require adjusting)
MySQL_database: minecraft_ukutils

#Tables in database (doesn't require adjusting)
MySQL_playerData: player_data