name: UKnetUtilities
version: 1.0
main: me.elgamer.UKnetUtilities.Main
description: UKnet Utilities Plugin

commands:
    tpll:
        usage: /<command> <lat> <lon>
        description: Tpll
    ll:
        aliases: [location, coordinates, co]
        usage: /<command>
        description: Get coordinates of player.